# coding: utf-8

"""
    Genezis Storages

    Сервис файловых хранилищ  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.storage_api import StorageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_storage_id_delete(self):
        """Test case for storage_id_delete

        Удалить данные хранилища  # noqa: E501
        """
        pass

    def test_storage_id_get(self):
        """Test case for storage_id_get

        Получить данные хранилища  # noqa: E501
        """
        pass

    def test_storage_id_put(self):
        """Test case for storage_id_put

        Обновить данные хранилища  # noqa: E501
        """
        pass

    def test_storage_post(self):
        """Test case for storage_post

        Добавление хранилища  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
