# coding: utf-8

"""
    Genezis Storages

    Сервис файловых хранилищ  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.storage_request import StorageRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestStorageRequest(unittest.TestCase):
    """StorageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageRequest(self):
        """Test StorageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.storage_request.StorageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
