# coding: utf-8

"""
    Genezis Storages

    Сервис файловых хранилищ  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.upload_api import UploadApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUploadApi(unittest.TestCase):
    """UploadApi unit test stubs"""

    def setUp(self):
        self.api = UploadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_post(self):
        """Test case for upload_post

        Загрузка файла  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
