# coding: utf-8

# flake8: noqa

"""
    Genezis Storages

    Сервис файловых хранилищ  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.storage_api import StorageApi
from swagger_client.api.upload_api import UploadApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.file import File
from swagger_client.models.storage_request import StorageRequest
from swagger_client.models.storage_response import StorageResponse
