# coding: utf-8

"""
    Genezis Storages

    Сервис файловых хранилищ  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class File(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'storage_id': 'int',
        'path': 'str',
        'file': 'str'
    }

    attribute_map = {
        'storage_id': 'storage_id',
        'path': 'path',
        'file': 'file'
    }

    def __init__(self, storage_id=None, path=None, file=None):  # noqa: E501
        """File - a model defined in Swagger"""  # noqa: E501
        self._storage_id = None
        self._path = None
        self._file = None
        self.discriminator = None
        if storage_id is not None:
            self.storage_id = storage_id
        if path is not None:
            self.path = path
        if file is not None:
            self.file = file

    @property
    def storage_id(self):
        """Gets the storage_id of this File.  # noqa: E501


        :return: The storage_id of this File.  # noqa: E501
        :rtype: int
        """
        return self._storage_id

    @storage_id.setter
    def storage_id(self, storage_id):
        """Sets the storage_id of this File.


        :param storage_id: The storage_id of this File.  # noqa: E501
        :type: int
        """

        self._storage_id = storage_id

    @property
    def path(self):
        """Gets the path of this File.  # noqa: E501


        :return: The path of this File.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this File.


        :param path: The path of this File.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def file(self):
        """Gets the file of this File.  # noqa: E501

        file to upload  # noqa: E501

        :return: The file of this File.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this File.

        file to upload  # noqa: E501

        :param file: The file of this File.  # noqa: E501
        :type: str
        """

        self._file = file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(File, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, File):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
